<a href="https://colab.research.google.com/github/Lathakh/Natural-language-processing/blob/main/WordEmbedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

for once sentene we are get a whole  vector representation  with dimention
suppose 2000 index ---> how much dimension you give that much it convert into vectors each word in the sentence

In [3]:

##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### Vocabulary size
voc_size=10000

#One Hot Representation

In [7]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[1519, 1405, 3133, 8607], [1519, 1405, 3133, 3246], [1519, 7551, 3133, 4721], [3327, 7799, 7492, 5691, 9460], [3327, 7799, 7492, 5691, 2528], [5811, 1519, 8253, 3133, 9181], [5510, 5963, 7576, 5691]]


# Word Embedding Represntation

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1519 1405 3133 8607]
 [   0    0    0    0 1519 1405 3133 3246]
 [   0    0    0    0 1519 7551 3133 4721]
 [   0    0    0 3327 7799 7492 5691 9460]
 [   0    0    0 3327 7799 7492 5691 2528]
 [   0    0    0 5811 1519 8253 3133 9181]
 [   0    0    0    0 5510 5963 7576 5691]]


In [12]:
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 115ms/step
[[[ 0.03114619  0.02027244 -0.03530773  0.04549123 -0.02035452
   -0.04511609 -0.01661057  0.04718126 -0.01885821 -0.03567372]
  [ 0.03114619  0.02027244 -0.03530773  0.04549123 -0.02035452
   -0.04511609 -0.01661057  0.04718126 -0.01885821 -0.03567372]
  [ 0.03114619  0.02027244 -0.03530773  0.04549123 -0.02035452
   -0.04511609 -0.01661057  0.04718126 -0.01885821 -0.03567372]
  [ 0.03114619  0.02027244 -0.03530773  0.04549123 -0.02035452
   -0.04511609 -0.01661057  0.04718126 -0.01885821 -0.03567372]
  [-0.04151402 -0.02153279 -0.04048923  0.0075706  -0.026295
   -0.01813211  0.02611354 -0.00485634  0.00036263  0.00684424]
  [-0.04019193 -0.01081331 -0.00838783 -0.03075981  0.01064218
    0.03885068  0.02143576 -0.0211156   0.0264349  -0.00545068]
  [-0.0461637   0.0371766   0.02725103 -0.04678335  0.01296195
   -0.04760127  0.00193822 -0.03577723 -0.01315017 -0.00280696]
  [ 0.00871968 -0.02535088 -0.046441    0.01896373 -0.030469

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 1519, 1405, 3133, 8607], dtype=int32)

for once sentene we are get a whole  vector representation  with dimention
suppose 2000 index ---> how much dimension you give that much it convert into vectors each word in the sentence

In [17]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 21ms/step
[[ 0.03114619  0.02027244 -0.03530773  0.04549123 -0.02035452 -0.04511609
  -0.01661057  0.04718126 -0.01885821 -0.03567372]
 [ 0.03114619  0.02027244 -0.03530773  0.04549123 -0.02035452 -0.04511609
  -0.01661057  0.04718126 -0.01885821 -0.03567372]
 [ 0.03114619  0.02027244 -0.03530773  0.04549123 -0.02035452 -0.04511609
  -0.01661057  0.04718126 -0.01885821 -0.03567372]
 [ 0.03114619  0.02027244 -0.03530773  0.04549123 -0.02035452 -0.04511609
  -0.01661057  0.04718126 -0.01885821 -0.03567372]
 [-0.04151402 -0.02153279 -0.04048923  0.0075706  -0.026295   -0.01813211
   0.02611354 -0.00485634  0.00036263  0.00684424]
 [-0.04019193 -0.01081331 -0.00838783 -0.03075981  0.01064218  0.03885068
   0.02143576 -0.0211156   0.0264349  -0.00545068]
 [-0.0461637   0.0371766   0.02725103 -0.04678335  0.01296195 -0.04760127
   0.00193822 -0.03577723 -0.01315017 -0.00280696]
 [ 0.00871968 -0.02535088 -0.046441    0.01896373 -0.03046985  0.0268204
